name: Build Rofi-Wayland

on:
  push:
    branches: [ "wayland" ]
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Original Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            meson ninja-build build-essential \
            libpango1.0-dev libstartup-notification0-dev \
            libxcb-ewmh-dev libxcb-icccm4-dev libxcb-randr0-dev \
            libxcb-util0-dev libxcb-xinerama0-dev libxcb-xkb-dev \
            libxcb-xrm-dev libxcb-cursor-dev libxkbcommon-dev \
            libxkbcommon-x11-dev libgdk-pixbuf2.0-dev \
            check flex bison libglib2.0-dev-bin doxygen \
            wayland-protocols libwayland-dev

      - name: Setup (Meson)
        run: meson setup builddir . -Db_lto=true

      - name: Build (Ninja)
        run: ninja -C builddir

      - name: Run Tests
        run: ninja -C builddir test

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rofi-wayland-binary
          path: builddir/rofi
